version: '3.8'

services:
  postgresql:
    image: docker.io/library/postgres:15.5-alpine3.19
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data
    env_file: .env
    ports:
      - '5455:5432'

  redis:
    image: docker.io/library/redis:7.2-alpine
    ports:
      - '6379:6379'
    volumes:
      - ./.data/redis:/data

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.5
    restart: unless-stopped
    env_file: .env
    command: start-dev --db=postgres --db-username=keycloak --db-password=keycloak --db-url=jdbc:postgresql://keycloak-postgresql:5432/keycloak
    depends_on:
      - keycloak-postgresql
    ports:
      - '8080:8080'

  keycloak-postgresql:
    image: docker.io/library/postgres:15.5-alpine3.19
    volumes:
      - ./.data/keycloak-postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_DB: keycloak
    ports:
      - '5432:5432'

  dashboard:
    image: budget-dashboard
    ports:
      - '4200:80'

  api:
    image: budget-api
    depends_on:
      - postgresql
      - redis
      - keycloak
    env_file: .env
    ports:
      - '3200:3200'
