version: '3.8'

services:
  postgresql:
    image: docker.io/library/postgres:15.5-alpine3.19
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}

  redis:
    image: docker.io/library/redis:7.2-alpine
    volumes:
      - ./.data/redis:/data

  dashboard:
    image: registry.devhub.me/budget-dashboard:latest
    ports:
      - '4200:80'

  api:
    image: registry.devhub.me/budget-api:latest
    depends_on:
      - postgresql
      - redis
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      KEYCLOAK_SERVER_URL: ${KEYCLOAK_SERVER_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_SECRET: ${KEYCLOAK_SECRET}
      KEYCLOAK_USE_NEST_LOGGER: ${KEYCLOAK_USE_NEST_LOGGER}
    ports:
      - '3200:3200'
