export enum RoutePathEnum {
  Auth = 'auth',
  SignIn = 'sign-in',
  Password = 'password',
  ResetRequest = 'reset-request',
  SetPassword = 'set-password',
  Done = 'done',
  Dashboard = 'dashboard',
  Records = 'records',
  Categories = 'categories',
  Budgets = 'budgets',
  Accounts = 'accounts',
  Providers = 'providers',
  Settings = 'settings',
  Profile = 'profile',
}
