export enum ApiPathEnum {
  Authentication = 'auth',
  SignIn = 'sign-in',
  Register = 'register',
  Users = 'users',
  Accounts = 'accounts',
  Budgets = 'budgets',
  BudgetSnapshots = 'budget-snapshots',
  Categories = 'categories',
  Records = 'records',
  Settings = 'settings',
  Jobs = 'jobs',
  Analytics = 'analytics',
  MerchantCategoryCodes = 'merchant-category-codes',
  PlannedPayments = 'planned-payments',
  PlannedPaymentSnapshots = 'planned-payment-snapshots',
  BudgetPlans = 'budget-plans',
  CurrencyRates = 'currency-rates',
}
