export enum CompanyEnum {
  Google = 'google',
  Youtube = 'youtube',
  Netflix = 'netflix',
  Spotify = 'spotify',
  PlayStation = 'playstation',
  Konzum = 'konzum',
  Plodine = 'plodine',
  DM = 'dm',
  Mueller = 'mueller',
  Spar = 'spar',
  IKEA = 'ikea',
  Lidl = 'lidl',
  Kaufland = 'kaufland',
  Mlinar = 'mlinar',
  PekaraDubravica = 'dubravica',
  Studenac = 'studenac',
}
