name: Build Dashboard and API docker images and deploy them

on:
  workflow_dispatch:
  push:
    branches: [main]
  # DELETE THIS
  pull_request:
    branches: [main]
jobs:
  #  build:
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: Checkout
  #        uses: actions/checkout@v4
  #      - name: Set up QEMU
  #        uses: docker/setup-qemu-action@v3
  #      - name: Set up Docker Buildx
  #        uses: docker/setup-buildx-action@v3
  #      - name: Login to Private docker registry
  #        uses: docker/login-action@v3
  #        with:
  #          registry: ${{ secrets.DOCKER_REGISTRY }}
  #          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
  #          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
  #      - name: Build dashboard docker image
  #        uses: docker/build-push-action@v5
  #        with:
  #          context: .
  #          file: ./dockerfiles/dashboard-prod
  #          push: true
  #          tags: registry.devhub.me/budget-dashboard:latest
  #      - name: Build API docker image
  #        uses: docker/build-push-action@v5
  #        with:
  #          context: .
  #          file: ./dockerfiles/api-prod
  #          push: true
  #          tags: registry.devhub.me/budget-api:latest
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          KEYCLOAK_SERVER_URL: ${{secrets.KEYCLOAK_SERVER_URL}}
          KEYCLOAK_REALM: ${{secrets.KEYCLOAK_REALM}}
          KEYCLOAK_CLIENT_ID: ${{secrets.KEYCLOAK_CLIENT_ID}}
          KEYCLOAK_SECRET: ${{secrets.KEYCLOAK_SECRET}}
          KEYCLOAK_USE_NEST_LOGGER: ${{secrets.KEYCLOAK_USE_NEST_LOGGER}}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          envs: DB_HOST, DB_PORT, DB_USERNAME, DB_PASSWORD, DB_NAME, REDIS_HOST, REDIS_PORT, KEYCLOAK_SERVER_URL, KEYCLOAK_REALM, KEYCLOAK_CLIENT_ID, KEYCLOAK_SECRET, KEYCLOAK_USE_NEST_LOGGER
          script: |
            cd ~
            git clone git@github.com-financial-project:pisarivskyi/financial-project.git
            git checkout feature/change-deployment-process
            mv financial-project/docker-compose.production.yml budget-app
            rm -rf financial-project
            cd budget-app
            docker compose up -d
            ls -la
