name: Deploy on server

on:
  # TODO: change it to main branch updated
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          AUTH0_ISSUER_URL: ${{ secrets.AUTH0_ISSUER_URL }}
          AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd ~
            rm -rf financial-project
            git clone git@github.com:pisarivskyi/financial-project.git
            cd financial-project
            npm ci
            npx nx run-many --all -t build
            rm -rf /var/www/budget-front/*
            cp -a ./dist/apps/dashboard/. /var/www/budget-front/
            cp -a ./dist/apps/api/. /var/www/budget-api/
            cd /var/www/budget-api/
            touch .env
            echo DB_HOST=$DB_HOST >> .env
            echo DB_PORT=$DB_PORT >> .env
            echo DB_USERNAME=$DB_USERNAME >> .env
            echo DB_PASSWORD=$DB_PASSWORD >> .env
            echo DB_NAME=$DB_NAME >> .env
            echo REDIS_HOST=$REDIS_HOST >> .env
            echo REDIS_PORT=$REDIS_PORT >> .env
            echo AUTH0_ISSUER_URL=$AUTH0_ISSUER_URL >> .env
            echo AUTH0_AUDIENCE=$AUTH0_AUDIENCE >> .env
            pm2 restart main.js
